apiVersion: v1
kind: Pod
metadata:
  name: stock-option-graph-app-pod
  labels:
    name: stock-graph-pod
    app: stock-graph-microservice-app

spec:
  containers:
    - name: graph-app
      image: kanishkmishra3538/service-stock
      ports:
        - containerPort: 80
