swagger: '2.0'
info:
  title: Exchange API
  version: '1.0'
paths:
  /hello:
    get:
      x-google-backend:
        address: https://34.42.225.8
      responses:
        '200':
          description: A successful response