swagger: '2.0'
info:
  title: News API
  version: '1.0'
paths:
  /hello:
    get:
      x-google-backend:
        address: https://34.46.175.76
      responses:
        '200':
          description: A successful response