apiVersion: v1
kind: Service
metadata:
  name: exchange
  labels:
    name: exchange-service
    app: stock-exchange-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    name: stock-exchange-pod
    app: stock-exchange-microservice-app
