apiVersion: v1
kind: Service
metadata:
  name: news
  labels:
    name: news-service
    app: stock-news-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    name: stock-news-pod
    app: stock-news-microservice-app
